import { auth } from "@/auth/auth";
import type { CollectionConfig } from "payload";

export const Users: CollectionConfig = {
  slug: "users",
  admin: {
    useAsTitle: "email",
  },
  auth: {
    disableLocalStrategy: true, // We should disable this since we use Better Auth now
    strategies: [
      {
        name: "better-auth",
        authenticate: async ({ headers, payload }) => {
          try {
            const userSession = await auth.api.getSession({ headers });

            if (!userSession || !userSession.user) return { user: null };

            const userData = await payload.findByID({
              collection: "users",
              id: userSession?.user?.id,
            });

            return {
              user: {
                ...userData,
                collection: "users",
              },
            };
          } catch (err) {
            payload.logger.error(err);
            return { user: null };
          }
        },
      },
    ],
  },
  endpoints: [
    {
      path: "/logout",
      method: "post",
      handler: async (req) => {
        await auth.api.signOut({
          headers: req.headers,
        });
        return Response.json(
          {
            message: "Token revoked successfully",
          },
          {
            status: 200,
            headers: req.headers,
          }
        );
      },
    },
  ],
  access: {
    admin: async ({ req }) => {
      const { success } = await auth.api.userHasPermission({
        // Only available when you setup the admin plugin
        body: {
          permissions: {
            adminDashboard: ["read"],
          },
          userId: req.user?.id,
        },
      });

      const isAllowed = typeof success === "boolean" ? success : false;

      return isAllowed;
    },
  },
  fields: [
    /*  id, createdAt, and updatedAt is autogenerated by Payload */
    /* Add more fields as you need */
    {
      name: "name",
      type: "text",
      required: true,
      index: true,
    },
    {
      name: "email",
      type: "text",
      required: true,
      unique: true,
      index: true,
    },
    {
      name: "emailVerified",
      type: "checkbox",
      required: true,
    },
    {
      name: "image",
      type: "text",
    },
    {
      name: "role",
      type: "select",
      required: true,
      options: ["user", "admin"],
      defaultValue: "user",
      admin: {
        description:
          "The user's role. Defaults to 'user'. Admins will have the 'admin' role.",
      },
    },
    {
      name: "banned",
      type: "checkbox",
      required: true,
      defaultValue: false,
      admin: {
        description: "Indicates whether the user is banned.",
      },
    },
    {
      name: "banReason",
      type: "text",
      admin: {
        description: "The reason for the user's ban.",
      },
    },
    {
      name: "banExpires",
      type: "date",
      admin: {
        description: "The date when the user's ban will expire.",
      },
    },
  ],
};
